name: Daily Repository Update

on:
  schedule:
    - cron: '12 14 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository so the workflow can work with the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make an update and include your email in the step name
      - name: Update file with current time (23f2003537@ds.study.iitm.ac.in)
        run: |
          # Create or update a file with the current date and time
          echo "Last update: $(date)" >> last_update.txt
          # Set the Git configuration for this commit
          git config --local user.email "23f2003537@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Action"
          # Stage the changes
          git add last_update.txt
          # Commit the changes. The || part prevents an error if there’s nothing new to commit.
          git commit -m "Daily update commit $(date)" || echo "No changes to commit"

      # Step 3: Push the changes back to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
